#!/bin/bash

set -eu

_USER="$(id -u)"

ARG1=${1:---help}

ARG2=${2:-""}

ARG3=${3:-""}

ARG4=${4:-""}

function Show_Help
{
    echo && cat ./docker/usage-help.txt && echo
}

function Start_User_Shell
{
    local _user="${1:-1000}"
    local _shell="${2:-zsh}"

    Create_Docker_Container ${_shell} ${_user}
}

function Create_Docker_Container
{
    local _command="${1:-zsh}"
    local _user="${2:-1000}"
    local _server_name="${3:-approov-protected-server}"
    local _port="${4:-5000}"

    sudo docker run \
        -it \
        --rm \
        --user "${_user}" \
        --env-file .env \
        --env "SERVER_NAME=server/${_server_name}.js" \
        --env "HTTP_PORT=${_port}" \
        --name "nodejs-express-${_server_name}-port-${_port}" \
        --publish "127.0.0.1:${_port}:5000" \
        --workdir "/home/node/workspace" \
        --volume "$PWD:/home/node/workspace" \
        approov/nodejs-express ${_command}
}

if [ "${ARG1}" == "build" ]
    then
        sudo docker build -t approov/nodejs-express ./docker
        exit 0
fi

if [ "${ARG1}" == "up" ] && [ "${ARG2}" == "approov-protected-server" ]
    then
        Create_Docker_Container "npm start" "${_USER}" "approov-protected-server" "${ARG3:-5000}"
        exit 0
fi

if [ "${ARG1}" == "up" ] && [ "${ARG2}" == "original-server" ]
    then
        Create_Docker_Container "node server/original-server.js" "${_USER}" "original-server" "${ARG3:-5001}"
        exit 0
fi

if [ "${ARG1}" == "start" ] && [ "${ARG2}" == "shell" ]
    then
        Start_User_Shell "${ARG3}" "${ARG4}"
        exit 0
fi


Show_Help
