version: "2.1"

services:

  node:
    image: approov/node-express-shapes-demo
    build: ./docker
    restart: always
    env_file: .env
    networks:
      - traefik
    command: "npm start"
    volumes:
      - ./:/home/node/workspace
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${NODEJS_EXPRESS_SHAPES_DOMAIN? Missing value for: NODEJS_EXPRESS_SHAPES_DOMAIN}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT? Missing value for: HTTP_PORT}"
      - "traefik.frontend.rule=Host:${NODEJS_EXPRESS_SHAPES_DOMAIN}"

networks:
  traefik:
    external: true
