version: "2.1"

services:

  dev:
    image: ${DOCKER_IMAGE:-approov/quickstart-nodejs-express-token-check:dev}
    build: .
    env_file:
      - .env
    working_dir: "/home/node/workspace"
    command: "npm start"
    volumes:
      - ./:/home/node/workspace
    ports:
      - 127.0.0.1:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    networks:
      - default

  node:
    image: ${DOCKER_IMAGE:-approov/quickstart-nodejs-express-token-check}
    build: .
    restart: always
    env_file: .env
    networks:
      - traefik
    command: "npm start"
    volumes:
      - ./:/home/node/workspace
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${SHAPES_NODEJS_EXPRESS_DOMAIN? Missing value for: SHAPES_NODEJS_EXPRESS_DOMAIN}"
      - "traefik.docker.network=traefik"
      - "traefik.port=${HTTP_PORT? Missing value for: HTTP_PORT}"
      - "traefik.frontend.rule=Host:${SHAPES_NODEJS_EXPRESS_DOMAIN}"

networks:
  traefik:
    external: true
